version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 909615039834.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t 909615039834.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/skybiz .
  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 909615039834.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/skybiz